### ISSUE TITLE
Review interpolation/blending model (value and spreadCount aspects)

### ISSUE THREAD

**Issue by natan-sinigaglia** [KairosResearchLab/Kairos#141]
Currently all AlchemX modules come with a separation for value and spreadCount models.
This is most of the time cryptic for users and also not really commonly useful.

- Interpolate node should have just an interpolation model pin

- blend node should have only blebbing model pin

It's up to the technique to deal with the value and spreadCount aspects, of needed

**Comment by gregsn** [comment]
agreed. 
If we at some point miss the ability to specify those models individually, we still could add it in the future:

all these are `IBlendingModel` implementations:
* A _SpreadBlendingModel (WithIndividualValueAndSpreadCountModels)_ taking an `IBlendingModel` for values of `Spread<T>` and another `IBlendingModel` for the spread count (Integer). (in the future)
* And still for now, when blending spreads, a user could also just use a simple `AdditiveBlendingModel`, where the blending function focuses on the values only and resamples the smaller spread in order to align with the bigger one by default. In other words, we pick one idea on how spreads get aligned and then the blending model only decides upon how the actual values get blended. 

Interpolation:
* A _SpreadInterpolationBlendingModel (WithIndividualValueAndSpreadCountModels)_ taking an `IInterpolationModel` for values of `Spread<T>` and another `IInterpolationModel` for the spread count (Integer). (in the future)
* But that would be just one of many possible Models for interpolating spreads. The branching idea where 3 values become 27, by branching them individually (handling the values and the topology at the same time) would be another one.
* For now when feeding a `BezierInterpolationModel` when using spreads we could interpret this as doing the bezier for the values (on resampled spreads) and then linearly sample more and more of the already built curves.

To me it sounds a bit as if we internally have a _SpreadInterpolation (Common)_, implementing `IInterpolationFunction`. This gets used inside the `Interpolate` node when confronted with spreads, but when the user didn't feed a spread-specific interpolation model. It's a simplification for the user. He could have used a _SpreadInterpolationModel (Common)_ that only accepts a model for the values since the spread count is taken care of by some standard idea.

All in all, I think that every data type could come with its own blending and interpolation ideas. The spread is just the first example for such a datatype. It is one that comes with different ways of specifying the blending or interpolation. 
* sometimes you want to handle values and spread counts as individual ideas
* sometimes you want to understand spreads as a bunch of values, where their count is a property of the value, not separate thing
* but for now you probably want to focus on the values and manage the spread count in some standard way

If we want to be future-proof this forbids registering one SpreadInterpolation implementation for the `Spread<T>`data type. We want the user longer-term to be able to build a tree of model nodes, that together describe the interpolation for a complex data type. And yet, for now, we want to have those common spread-specific interpolators that jump in when you just connect a BezierInterpolator.

**Comment by gregsn** [comment]
https://github.com/KairosResearchLab/Kairos/issues/197
